//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.530
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharpToGo.App.Android
{
	
	
	public partial class Resource
	{
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int Namespaces = 2131099648;
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int defaultValue = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int maxValue = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int minValue = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int suffix = 2130771971;
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050008
			public const int SyntaxHighlight = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int WindowTitleBackground = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int black = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int blue = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int codecompletion_highlight = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int offwhite = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int red = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int white = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int yellow = 2131034113;
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int CodeCompletionItemBackgroundFocusedSelector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int CodeCompletionItemBackgroundSelector = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int CodeCompletionItemTextSelector = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Error = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ExecutionHistoryListSelector = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ExecutionHistoryListSelectorPressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ExecutionHistoryListSelectorSelected = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_menu_add = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int ic_menu_info_details = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int ic_menu_preferences = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int ic_menu_revert = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int ic_menu_set_as = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Info = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int Run = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Splash = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int Warning = 2130837520;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0015
			public const int About = 2131361813;
			
			// aapt resource value: 0x7f0a0011
			public const int Clear = 2131361809;
			
			// aapt resource value: 0x7f0a0000
			public const int Completion = 2131361792;
			
			// aapt resource value: 0x7f0a000b
			public const int ConsoleIcon = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int ConsoleOutput = 2131361804;
			
			// aapt resource value: 0x7f0a000a
			public const int ConsoleOutputContainer = 2131361802;
			
			// aapt resource value: 0x7f0a0016
			public const int CopyMessage = 2131361814;
			
			// aapt resource value: 0x7f0a000d
			public const int Errors = 2131361805;
			
			// aapt resource value: 0x7f0a0001
			public const int Icon = 2131361793;
			
			// aapt resource value: 0x7f0a0005
			public const int Input = 2131361797;
			
			// aapt resource value: 0x7f0a0004
			public const int InputContainer = 2131361796;
			
			// aapt resource value: 0x7f0a0003
			public const int InputOuterContainer = 2131361795;
			
			// aapt resource value: 0x7f0a000e
			public const int Label = 2131361806;
			
			// aapt resource value: 0x7f0a0002
			public const int MessageText = 2131361794;
			
			// aapt resource value: 0x7f0a0008
			public const int NamespaceOption = 2131361800;
			
			// aapt resource value: 0x7f0a0012
			public const int Namespaces = 2131361810;
			
			// aapt resource value: 0x7f0a0010
			public const int NamespacesList = 2131361808;
			
			// aapt resource value: 0x7f0a0009
			public const int Output = 2131361801;
			
			// aapt resource value: 0x7f0a0007
			public const int Results = 2131361799;
			
			// aapt resource value: 0x7f0a0006
			public const int Run = 2131361798;
			
			// aapt resource value: 0x7f0a0017
			public const int Search = 2131361815;
			
			// aapt resource value: 0x7f0a000f
			public const int SeekBar = 2131361807;
			
			// aapt resource value: 0x7f0a0014
			public const int Settings = 2131361812;
			
			// aapt resource value: 0x7f0a0013
			public const int Variables = 2131361811;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CodeCompletionItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ErrorMessageItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int NamespaceOption = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ResultItem = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int TimeoutDialogPreference = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int UpdateNamespaces = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int WarningMessageItem = 2130903047;
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int MainMenu = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int MessageContextMenu = 2131296257;
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070020
			public const int AboutContent = 2131165216;
			
			// aapt resource value: 0x7f07001f
			public const int AboutOkButton = 2131165215;
			
			// aapt resource value: 0x7f07001e
			public const int AboutTitle = 2131165214;
			
			// aapt resource value: 0x7f070000
			public const int ApplicationName = 2131165184;
			
			// aapt resource value: 0x7f070014
			public const int ClassMessage = 2131165204;
			
			// aapt resource value: 0x7f070008
			public const int ClearSessionProgressText = 2131165192;
			
			// aapt resource value: 0x7f070007
			public const int ClearSessionProgressTitle = 2131165191;
			
			// aapt resource value: 0x7f070010
			public const int CopyMessage = 2131165200;
			
			// aapt resource value: 0x7f070003
			public const int InputHint = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int NoOutput = 2131165188;
			
			// aapt resource value: 0x7f07000f
			public const int NoVariables = 2131165199;
			
			// aapt resource value: 0x7f07000d
			public const int OptionsMenu_About = 2131165197;
			
			// aapt resource value: 0x7f070009
			public const int OptionsMenu_Clear = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int OptionsMenu_Namespaces = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int OptionsMenu_Settings = 2131165196;
			
			// aapt resource value: 0x7f07000b
			public const int OptionsMenu_Variables = 2131165195;
			
			// aapt resource value: 0x7f070022
			public const int RemoveNamespaceMessageContent = 2131165218;
			
			// aapt resource value: 0x7f070023
			public const int RemoveNamespaceMessageOkButton = 2131165219;
			
			// aapt resource value: 0x7f070021
			public const int RemoveNamespaceMessageTitle = 2131165217;
			
			// aapt resource value: 0x7f070006
			public const int RunningCodeProgressText = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int RunningCodeProgressTitle = 2131165189;
			
			// aapt resource value: 0x7f070011
			public const int SearchForMessage = 2131165201;
			
			// aapt resource value: 0x7f070002
			public const int SettingsLabel = 2131165186;
			
			// aapt resource value: 0x7f07001d
			public const int Settings_DoubleEnterSummary = 2131165213;
			
			// aapt resource value: 0x7f07001c
			public const int Settings_DoubleEnterTitle = 2131165212;
			
			// aapt resource value: 0x7f07001b
			public const int Settings_MultiLineEditingSummary = 2131165211;
			
			// aapt resource value: 0x7f07001a
			public const int Settings_MultiLineEditingTitle = 2131165210;
			
			// aapt resource value: 0x7f070019
			public const int Settings_SaveNamespacesSummary = 2131165209;
			
			// aapt resource value: 0x7f070018
			public const int Settings_SaveNamespacesTitle = 2131165208;
			
			// aapt resource value: 0x7f070017
			public const int Settings_TimeoutSuffix = 2131165207;
			
			// aapt resource value: 0x7f070016
			public const int Settings_TimeoutSummary = 2131165206;
			
			// aapt resource value: 0x7f070015
			public const int Settings_TimeoutTitle = 2131165205;
			
			// aapt resource value: 0x7f070012
			public const int TimeoutMessage = 2131165202;
			
			// aapt resource value: 0x7f070001
			public const int UpdateNamespacesActivityLabel = 2131165185;
			
			// aapt resource value: 0x7f070013
			public const int UsingMessage = 2131165203;
			
			// aapt resource value: 0x7f07000e
			public const int VariablesDialogTitle = 2131165198;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080001
			public const int ApplicationTheme = 2131230721;
			
			// aapt resource value: 0x7f080007
			public const int CodeCompletionInput = 2131230727;
			
			// aapt resource value: 0x7f08000c
			public const int ConsoleOutput = 2131230732;
			
			// aapt resource value: 0x7f08000a
			public const int ErrorMessage = 2131230730;
			
			// aapt resource value: 0x7f080003
			public const int ExecutionHistoryList = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int ExecutionResultInput = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int ExecutionResultOutput = 2131230726;
			
			// aapt resource value: 0x7f08000f
			public const int InputContainer = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int InputOuterContainer = 2131230736;
			
			// aapt resource value: 0x7f080009
			public const int Message = 2131230729;
			
			// aapt resource value: 0x7f08000d
			public const int MessageContainer = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int MessageIcon = 2131230734;
			
			// aapt resource value: 0x7f080011
			public const int NamespaceList = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int NamespaceOption = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int PreferencesTheme = 2131230739;
			
			// aapt resource value: 0x7f080004
			public const int ResultItem = 2131230724;
			
			// aapt resource value: 0x7f080008
			public const int RunButton = 2131230728;
			
			// aapt resource value: 0x7f080000
			public const int Theme_Splash = 2131230720;
			
			// aapt resource value: 0x7f080014
			public const int TimeoutPreferenceLabel = 2131230740;
			
			// aapt resource value: 0x7f08000b
			public const int WarningMessage = 2131230731;
			
			// aapt resource value: 0x7f080002
			public const int WindowTitleBackground = 2131230722;
			
			private Style()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7f040000
			public const int Settings = 2130968576;
			
			private Xml()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SeekBarPreference = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 2
			public const int SeekBarPreference_defaultValue = 2;
			
			// aapt resource value: 1
			public const int SeekBarPreference_maxValue = 1;
			
			// aapt resource value: 0
			public const int SeekBarPreference_minValue = 0;
			
			// aapt resource value: 3
			public const int SeekBarPreference_suffix = 3;
			
			private Styleable()
			{
			}
		}
	}
}
